
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mavenapp
  name: mavenapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8083
      nodePort: 30080
      protocol: TCP
  selector:
    app: mavenapp
